import { writeFile } from "node:fs/promises";
import { createServer } from "vite";
import { png } from "./lib/raster.mjs";

// Every size uses the brand geometry, including the front/back band split.
const vite = await createServer({
  server: { middlewareMode: true, watch: null },
  appType: "custom",
  logLevel: "error",
});
try {
  const { createPendantProfile } = await vite.ssrLoadModule("/src/brand/pendant-model.ts");
  const { shape, opening } = createPendantProfile();
  const point = (p) => `${(50 + p.x * 20).toFixed(3)} ${(50 - p.y * 20).toFixed(3)}`;
  const path = (p) => `M ${point(p.curves[0].v0)} ` + p.curves.map(c => `C ${point(c.v1)} ${point(c.v2)} ${point(c.v3)}`).join(" ") + " Z";
  const body = `${path(shape)} ${path(opening)}`;
  const orbitPoint = (t) => {
    const x = .82 * Math.cos(t), y = .34 * .69 * Math.sin(t);
    return { x: (x + y) / Math.SQRT2, y: (-x + y) / Math.SQRT2 };
  };
  const arc = (start) => Array.from({length: 65}, (_, i) => `${i ? "L" : "M"} ${point(orbitPoint(start + i / 64 * Math.PI))}`).join(" ");
  const back = arc(Math.PI), front = arc(0);
  const markData = { back: [{ d: back, fill: false, width: 2.8 }], body: [{ d: body, fill: true, evenOdd: true }], front: [{ d: front, fill: false, width: 2.8 }], gapWidth: 5.8, frontPath: front };
  await writeFile("src/brand/pendant-mark.ts", `// Generated by npm run icons from the actual pendant profile.\nexport const pendantMark = ${JSON.stringify(markData, null, 2)};\n`);
  // Slightly heavier edges preserve the open frame at browser-tab sizes.
  const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="#141416"/><defs><mask id="crossing"><rect width="100" height="100" fill="white"/><path d="${front}" fill="none" stroke="black" stroke-width="7"/></mask></defs><g transform="translate(6 6) scale(.88)"><path d="${back}" fill="none" stroke="#efeee9" stroke-width="4"/><path d="${body}" fill="#efeee9" fill-rule="evenodd" stroke="#efeee9" stroke-width="1.5" mask="url(#crossing)"/><path d="${front}" fill="none" stroke="#b9c9ff" stroke-width="4"/></g></svg>`;
  const stellar = icon.replace('<rect width="100" height="100" rx="20" fill="#141416"/>', "");
  await writeFile("public/favicon.svg", icon + "\n");
  await writeFile("public/stellar.svg", stellar + "\n");
  // Deterministic supersampled raster fallbacks, with no native/image dependency.
  const outer = shape.getPoints(40), inner = opening.getPoints(40);
  const inside = (points, x, y) => {
    let result = false;
    for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
      const a = points[i], b = points[j];
      if ((a.y > y) !== (b.y > y) && x < (b.x - a.x) * (y - a.y) / (b.y - a.y) + a.x) result = !result;
    }
    return result;
  };
  const distance = (points, x, y) => {
    let best = Infinity;
    for (let i = 1; i < points.length; i++) {
      const a = points[i - 1], b = points[i], dx = b.x - a.x, dy = b.y - a.y;
      const t = Math.max(0, Math.min(1, ((x - a.x) * dx + (y - a.y) * dy) / (dx * dx + dy * dy)));
      best = Math.min(best, Math.hypot(x - a.x - t * dx, y - a.y - t * dy));
    }
    return best;
  };
  const frontPoints = Array.from({length: 65}, (_, i) => orbitPoint(i / 64 * Math.PI));
  const backPoints = Array.from({length: 65}, (_, i) => orbitPoint(Math.PI + i / 64 * Math.PI));
  const raster = size => {
    const pixels = new Uint8Array(size * size * 3), samples = 4;
    for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
      const sum = [0, 0, 0];
      for (let sy = 0; sy < samples; sy++) for (let sx = 0; sx < samples; sx++) {
        const u = (((x + (sx + .5) / samples) / size * 100 - 6) / .88 - 50) / 20;
        const v = (50 - ((y + (sy + .5) / samples) / size * 100 - 6) / .88) / 20;
        const f = distance(frontPoints, u, v), b = distance(backPoints, u, v);
        const metal = (inside(outer, u, v) && !inside(inner, u, v)) || Math.min(distance(outer, u, v), distance(inner, u, v)) < .0375;
        const color = f < .1 ? [185,201,255] : (metal && f > .175) || b < .1 ? [239,238,233] : [20,20,22];
        for (let c = 0; c < 3; c++) sum[c] += color[c];
      }
      for (let c = 0; c < 3; c++) pixels[(y * size + x) * 3 + c] = Math.round(sum[c] / (samples * samples));
    }
    return png(size, size, pixels, 3);
  };
  await writeFile("public/apple-touch-icon.png", raster(180));
  const frames = [16,32,48].map(size => ({size, data:raster(size)}));
  const header = Buffer.alloc(6 + frames.length * 16);
  header.writeUInt16LE(1, 2); header.writeUInt16LE(frames.length, 4);
  let offset = header.length;
  frames.forEach(({size,data}, i) => {
    const p = 6 + i * 16;
    header[p] = size; header[p + 1] = size;
    header.writeUInt16LE(1,p + 4); header.writeUInt16LE(24,p + 6);
    header.writeUInt32LE(data.length,p + 8); header.writeUInt32LE(offset,p + 12);
    offset += data.length;
  });
  await writeFile("public/favicon.ico", Buffer.concat([header,...frames.map(f => f.data)]));
  console.log("Generated the flat pendant mark, SVG/ICO favicons, and touch icon.");
} finally {
  await vite.close();
}
